platform :ios, '11.0'
inhibit_all_warnings!
workspace 'YZChat.xcworkspace'

def abstract_pods
  pod 'Masonry'
  pod 'AFNetworking', '~> 4.0'
  pod 'IQKeyboardManager'
#  pod 'MJExtension'
#  pod 'FCFileManager'
#  pod 'BlocksKit'
#  pod 'Bugly'
  pod 'ZXingObjC'
  pod 'MMLayout', '~> 0.2.0'
  pod 'SDWebImage', '~> 5.9.0'
  pod 'ReactiveObjC', '~> 3.1.1'
  pod 'Toast', '~> 4.0.0'
#  pod 'TXLiteAVSDK_TRTC', '~> 7.8.9515'
  pod 'TXLiteAVSDK_Professional'

#  pod 'AMap3DMap-NO-IDFA'
  pod 'AMapSearch-NO-IDFA'
#  pod 'AMapLocation-NO-IDFA'

end

def project_pods
  pod 'YYModel'
  pod 'YYText'
  pod 'QMUIKit'
end

target 'YZChat_Example' do
  abstract_pods
  project_pods
end

target 'YZChat_Example_Pod' do
  pod 'YZChat', :path => '../'
end

target 'YZChat' do
  project '../YZChatFramework/YZChat.xcodeproj'

  abstract_pods
end
