platform :ios, '11.0'
workspace 'YZChat.xcworkspace'

def abstract_pods
  pod 'QMUIKit'
  pod 'Masonry'
  pod 'YYModel'
  pod 'YYText'
  pod 'AFNetworking', '~> 4.0'
  pod 'IQKeyboardManager'
  pod 'MJExtension'
  pod 'FCFileManager'
  pod 'BlocksKit'
  pod 'Bugly'
  pod 'ZXingObjC'

  pod 'MMLayout', '~> 0.2.0'
  pod 'SDWebImage', '~> 5.9.0'
  pod 'ReactiveObjC', '~> 3.1.1'
  pod 'Toast', '~> 4.0.0'
  pod 'TXLiteAVSDK_TRTC', '~> 7.8.9515'

  pod 'AMap3DMap-NO-IDFA'
  pod 'AMapSearch-NO-IDFA'
end

target 'YZChat_Example' do
  abstract_pods
end

target 'YZChat_Example_Pod' do
  pod 'YZChat', :path => '../'
end

target 'YZChat' do
  project '../YZChatFramework/YZChat.xcodeproj'

  abstract_pods
end
